#include "nes.h"

namespace nes {

#ifdef NES_CPU_COUNT_OPS
uint64_t g_opCounts[256];
#endif

// NB: splicing an inline RAM fast path in here (addr < 0x2000 -> nes_.ram)
// measured *slower* on hardware — 30.8 -> 28.5 fps — because the extra branch
// at every operand fetch grows CPU::step past what the Xtensa I-cache holds.
// The nested call chain is not the bottleneck it looks like; leave it alone.
uint8_t CPU::read(uint16_t addr) { return nes_.cpuRead(addr); }
void CPU::write(uint16_t addr, uint8_t v) { nes_.cpuWrite(addr, v); }
uint16_t CPU::read16(uint16_t addr) { return read(addr) | (read(addr + 1) << 8); }
void CPU::push(uint8_t v) { write(0x100 | sp--, v); }
uint8_t CPU::pop() { return read(0x100 | ++sp); }

uint8_t CPU::status(bool brk) const {
    return (fN << 7) | (fV << 6) | 0x20 | (brk << 4) | (fD << 3) | (fI << 2) | (fZ << 1) | (uint8_t)fC;
}
// clang-format off
// P レジスタの各ビットを縦に並べた 1 行。展開して 6 行にすると status() の
// 逆写像であることが読み取りづらくなるため整形対象から外す
void CPU::setStatus(uint8_t p) {
    fN = p & 0x80; fV = p & 0x40; fD = p & 0x08; fI = p & 0x04; fZ = p & 0x02; fC = p & 0x01;
}
// clang-format on

void CPU::reset() {
    pc = read16(0xFFFC);
    sp = 0xFD;
    fI = true;
    nmiPending_ = false;
    irqLine_ = false;
    stall_ = 0;
}

// Addressing modes: each returns effective address; pageCrossed set for +1 cycle modes
namespace {
inline bool samePage(uint16_t a, uint16_t b) { return (a & 0xFF00) == (b & 0xFF00); }
}

void CPU::branch(bool cond, int& cycles) {
    int8_t off = (int8_t)read(pc++);
    if (cond) {
        uint16_t old = pc;
        pc += off;
        cycles += samePage(old, pc) ? 1 : 2;
    }
}

// ---- opcode handlers (generated by scratchpad/gen_ops.py) ----
// Bodies are transcribed from the original switch statement; cycle counts,
// page-cross penalties and dummy read/write ordering are unchanged.

// clang-format off
// 以下 256 個のハンドラと OPS[] は「1 行 = 1 オペコード」の表。オペコード順に
// 並べて隣接命令との差分を追えることが可読性の要なので、機械整形で複数行に
// 展開させない (展開すると 1500 行以上増え、表として読めなくなる)

int CPU::op00() { pc++; push(pc >> 8); push(pc & 0xFF); push(status(true)); fI = true; pc = read16(0xFFFE); return 7; }
int CPU::op01() { a |= read(amIzx()); setZN(a); return 6; }
int CPU::op02() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::op03() { uint16_t ad = amIzx(); uint8_t m = read(ad); fC = m & 0x80; m <<= 1; write(ad, m); a |= m; setZN(a); return 8; }
int CPU::op04() { pc++; return 3; }
int CPU::op05() { a |= read(amZp()); setZN(a); return 3; }
int CPU::op06() { uint16_t ad = amZp(); uint8_t m = read(ad); write(ad, m); write(ad, opAslv(m)); return 5; }
int CPU::op07() { uint16_t ad = amZp(); uint8_t m = read(ad); fC = m & 0x80; m <<= 1; write(ad, m); a |= m; setZN(a); return 5; }
int CPU::op08() { push(status(true)); return 3; }
int CPU::op09() { a |= read(amImm()); setZN(a); return 2; }
int NES_HOT CPU::op0A() { a = opAslv(a); return 2; }
int CPU::op0B() { a &= read(amImm()); setZN(a); fC = fN; return 2; }
int CPU::op0C() { pc += 2; return 4; }
int CPU::op0D() { a |= read(amAbs()); setZN(a); return 4; }
int CPU::op0E() { uint16_t ad = amAbs(); uint8_t m = read(ad); write(ad, m); write(ad, opAslv(m)); return 6; }
int CPU::op0F() { uint16_t ad = amAbs(); uint8_t m = read(ad); fC = m & 0x80; m <<= 1; write(ad, m); a |= m; setZN(a); return 6; }
int CPU::op10() { int cycles = 2; branch(!fN, cycles); return cycles; }
int CPU::op11() { a |= read(amIzy()); setZN(a); return 5 + crossed_; }
int CPU::op12() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::op13() { uint16_t ad = amIzy(); uint8_t m = read(ad); fC = m & 0x80; m <<= 1; write(ad, m); a |= m; setZN(a); return 8; }
int CPU::op14() { pc++; return 4; }
int CPU::op15() { a |= read(amZpx()); setZN(a); return 4; }
int CPU::op16() { uint16_t ad = amZpx(); uint8_t m = read(ad); write(ad, m); write(ad, opAslv(m)); return 6; }
int CPU::op17() { uint16_t ad = amZpx(); uint8_t m = read(ad); fC = m & 0x80; m <<= 1; write(ad, m); a |= m; setZN(a); return 6; }
int NES_HOT CPU::op18() { fC = false; return 2; }
int CPU::op19() { a |= read(amAby()); setZN(a); return 4 + crossed_; }
int CPU::op1A() { return 2; }
int CPU::op1B() { uint16_t ad = amAby(); uint8_t m = read(ad); fC = m & 0x80; m <<= 1; write(ad, m); a |= m; setZN(a); return 7; }
int CPU::op1C() { amAbx(); return 4 + crossed_; }
int CPU::op1D() { a |= read(amAbx()); setZN(a); return 4 + crossed_; }
int CPU::op1E() { uint16_t ad = amAbx(); uint8_t m = read(ad); write(ad, m); write(ad, opAslv(m)); return 7; }
int CPU::op1F() { uint16_t ad = amAbx(); uint8_t m = read(ad); fC = m & 0x80; m <<= 1; write(ad, m); a |= m; setZN(a); return 7; }
int NES_HOT CPU::op20() { uint16_t target = read16(pc); uint16_t ret = pc + 1; push(ret >> 8); push(ret & 0xFF); pc = target; return 6; }
int CPU::op21() { a &= read(amIzx()); setZN(a); return 6; }
int CPU::op22() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::op23() { uint16_t ad = amIzx(); uint8_t m = read(ad); bool c = fC; fC = m & 0x80; m = (m << 1) | c; write(ad, m); a &= m; setZN(a); return 8; }
int CPU::op24() { uint8_t m = read(amZp()); fZ = (a & m) == 0; fV = m & 0x40; fN = m & 0x80; return 3; }
int CPU::op25() { a &= read(amZp()); setZN(a); return 3; }
int CPU::op26() { uint16_t ad = amZp(); uint8_t m = read(ad); write(ad, m); write(ad, opRolv(m)); return 5; }
int CPU::op27() { uint16_t ad = amZp(); uint8_t m = read(ad); bool c = fC; fC = m & 0x80; m = (m << 1) | c; write(ad, m); a &= m; setZN(a); return 5; }
int CPU::op28() { setStatus(pop()); return 4; }
int NES_HOT CPU::op29() { a &= read(amImm()); setZN(a); return 2; }
int CPU::op2A() { a = opRolv(a); return 2; }
int CPU::op2B() { a &= read(amImm()); setZN(a); fC = fN; return 2; }
int NES_HOT CPU::op2C() { uint8_t m = read(amAbs()); fZ = (a & m) == 0; fV = m & 0x40; fN = m & 0x80; return 4; }
int CPU::op2D() { a &= read(amAbs()); setZN(a); return 4; }
int CPU::op2E() { uint16_t ad = amAbs(); uint8_t m = read(ad); write(ad, m); write(ad, opRolv(m)); return 6; }
int CPU::op2F() { uint16_t ad = amAbs(); uint8_t m = read(ad); bool c = fC; fC = m & 0x80; m = (m << 1) | c; write(ad, m); a &= m; setZN(a); return 6; }
int CPU::op30() { int cycles = 2; branch(fN, cycles); return cycles; }
int CPU::op31() { a &= read(amIzy()); setZN(a); return 5 + crossed_; }
int CPU::op32() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::op33() { uint16_t ad = amIzy(); uint8_t m = read(ad); bool c = fC; fC = m & 0x80; m = (m << 1) | c; write(ad, m); a &= m; setZN(a); return 8; }
int CPU::op34() { pc++; return 4; }
int CPU::op35() { a &= read(amZpx()); setZN(a); return 4; }
int CPU::op36() { uint16_t ad = amZpx(); uint8_t m = read(ad); write(ad, m); write(ad, opRolv(m)); return 6; }
int CPU::op37() { uint16_t ad = amZpx(); uint8_t m = read(ad); bool c = fC; fC = m & 0x80; m = (m << 1) | c; write(ad, m); a &= m; setZN(a); return 6; }
int NES_HOT CPU::op38() { fC = true; return 2; }
int CPU::op39() { a &= read(amAby()); setZN(a); return 4 + crossed_; }
int CPU::op3A() { return 2; }
int CPU::op3B() { uint16_t ad = amAby(); uint8_t m = read(ad); bool c = fC; fC = m & 0x80; m = (m << 1) | c; write(ad, m); a &= m; setZN(a); return 7; }
int CPU::op3C() { amAbx(); return 4 + crossed_; }
int CPU::op3D() { a &= read(amAbx()); setZN(a); return 4 + crossed_; }
int CPU::op3E() { uint16_t ad = amAbx(); uint8_t m = read(ad); write(ad, m); write(ad, opRolv(m)); return 7; }
int CPU::op3F() { uint16_t ad = amAbx(); uint8_t m = read(ad); bool c = fC; fC = m & 0x80; m = (m << 1) | c; write(ad, m); a &= m; setZN(a); return 7; }
int CPU::op40() { setStatus(pop()); pc = pop() | (pop() << 8); return 6; }
int CPU::op41() { a ^= read(amIzx()); setZN(a); return 6; }
int CPU::op42() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::op43() { uint16_t ad = amIzx(); uint8_t m = read(ad); fC = m & 1; m >>= 1; write(ad, m); a ^= m; setZN(a); return 8; }
int CPU::op44() { pc++; return 3; }
int CPU::op45() { a ^= read(amZp()); setZN(a); return 3; }
int CPU::op46() { uint16_t ad = amZp(); uint8_t m = read(ad); write(ad, m); write(ad, opLsrv(m)); return 5; }
int CPU::op47() { uint16_t ad = amZp(); uint8_t m = read(ad); fC = m & 1; m >>= 1; write(ad, m); a ^= m; setZN(a); return 5; }
int CPU::op48() { push(a); return 3; }
int CPU::op49() { a ^= read(amImm()); setZN(a); return 2; }
int NES_HOT CPU::op4A() { a = opLsrv(a); return 2; }
int CPU::op4B() { a &= read(amImm()); a = opLsrv(a); return 2; }
int NES_HOT CPU::op4C() { pc = read16(pc); return 3; }
int CPU::op4D() { a ^= read(amAbs()); setZN(a); return 4; }
int CPU::op4E() { uint16_t ad = amAbs(); uint8_t m = read(ad); write(ad, m); write(ad, opLsrv(m)); return 6; }
int CPU::op4F() { uint16_t ad = amAbs(); uint8_t m = read(ad); fC = m & 1; m >>= 1; write(ad, m); a ^= m; setZN(a); return 6; }
int NES_HOT CPU::op50() { int cycles = 2; branch(!fV, cycles); return cycles; }
int CPU::op51() { a ^= read(amIzy()); setZN(a); return 5 + crossed_; }
int CPU::op52() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::op53() { uint16_t ad = amIzy(); uint8_t m = read(ad); fC = m & 1; m >>= 1; write(ad, m); a ^= m; setZN(a); return 8; }
int CPU::op54() { pc++; return 4; }
int CPU::op55() { a ^= read(amZpx()); setZN(a); return 4; }
int CPU::op56() { uint16_t ad = amZpx(); uint8_t m = read(ad); write(ad, m); write(ad, opLsrv(m)); return 6; }
int CPU::op57() { uint16_t ad = amZpx(); uint8_t m = read(ad); fC = m & 1; m >>= 1; write(ad, m); a ^= m; setZN(a); return 6; }
int CPU::op58() { fI = false; return 2; }
int CPU::op59() { a ^= read(amAby()); setZN(a); return 4 + crossed_; }
int CPU::op5A() { return 2; }
int CPU::op5B() { uint16_t ad = amAby(); uint8_t m = read(ad); fC = m & 1; m >>= 1; write(ad, m); a ^= m; setZN(a); return 7; }
int CPU::op5C() { amAbx(); return 4 + crossed_; }
int CPU::op5D() { a ^= read(amAbx()); setZN(a); return 4 + crossed_; }
int CPU::op5E() { uint16_t ad = amAbx(); uint8_t m = read(ad); write(ad, m); write(ad, opLsrv(m)); return 7; }
int CPU::op5F() { uint16_t ad = amAbx(); uint8_t m = read(ad); fC = m & 1; m >>= 1; write(ad, m); a ^= m; setZN(a); return 7; }
int NES_HOT CPU::op60() { pc = (pop() | (pop() << 8)) + 1; return 6; }
int CPU::op61() { opAdcv(read(amIzx())); return 6; }
int CPU::op62() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::op63() { uint16_t ad = amIzx(); uint8_t m = read(ad); bool c = fC; fC = m & 1; m = (m >> 1) | (c << 7); write(ad, m); opAdcv(m); return 8; }
int CPU::op64() { pc++; return 3; }
int CPU::op65() { opAdcv(read(amZp())); return 3; }
int CPU::op66() { uint16_t ad = amZp(); uint8_t m = read(ad); write(ad, m); write(ad, opRorv(m)); return 5; }
int CPU::op67() { uint16_t ad = amZp(); uint8_t m = read(ad); bool c = fC; fC = m & 1; m = (m >> 1) | (c << 7); write(ad, m); opAdcv(m); return 5; }
int CPU::op68() { a = pop(); setZN(a); return 4; }
int NES_HOT CPU::op69() { opAdcv(read(amImm())); return 2; }
int CPU::op6A() { a = opRorv(a); return 2; }
int CPU::op6B() { a &= read(amImm()); a = (a >> 1) | (fC << 7); setZN(a); fC = a & 0x40; fV = ((a >> 6) ^ (a >> 5)) & 1; return 2; }
int CPU::op6C() { uint16_t p = read16(pc); uint16_t lo = read(p); uint16_t hi = read((p & 0xFF00) | ((p + 1) & 0xFF)); pc = lo | (hi << 8); return 5; }
int CPU::op6D() { opAdcv(read(amAbs())); return 4; }
int CPU::op6E() { uint16_t ad = amAbs(); uint8_t m = read(ad); write(ad, m); write(ad, opRorv(m)); return 6; }
int CPU::op6F() { uint16_t ad = amAbs(); uint8_t m = read(ad); bool c = fC; fC = m & 1; m = (m >> 1) | (c << 7); write(ad, m); opAdcv(m); return 6; }
int NES_HOT CPU::op70() { int cycles = 2; branch(fV, cycles); return cycles; }
int CPU::op71() { opAdcv(read(amIzy())); return 5 + crossed_; }
int CPU::op72() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::op73() { uint16_t ad = amIzy(); uint8_t m = read(ad); bool c = fC; fC = m & 1; m = (m >> 1) | (c << 7); write(ad, m); opAdcv(m); return 8; }
int CPU::op74() { pc++; return 4; }
int CPU::op75() { opAdcv(read(amZpx())); return 4; }
int CPU::op76() { uint16_t ad = amZpx(); uint8_t m = read(ad); write(ad, m); write(ad, opRorv(m)); return 6; }
int CPU::op77() { uint16_t ad = amZpx(); uint8_t m = read(ad); bool c = fC; fC = m & 1; m = (m >> 1) | (c << 7); write(ad, m); opAdcv(m); return 6; }
int CPU::op78() { fI = true; return 2; }
int CPU::op79() { opAdcv(read(amAby())); return 4 + crossed_; }
int CPU::op7A() { return 2; }
int CPU::op7B() { uint16_t ad = amAby(); uint8_t m = read(ad); bool c = fC; fC = m & 1; m = (m >> 1) | (c << 7); write(ad, m); opAdcv(m); return 7; }
int CPU::op7C() { amAbx(); return 4 + crossed_; }
int CPU::op7D() { opAdcv(read(amAbx())); return 4 + crossed_; }
int CPU::op7E() { uint16_t ad = amAbx(); uint8_t m = read(ad); write(ad, m); write(ad, opRorv(m)); return 7; }
int CPU::op7F() { uint16_t ad = amAbx(); uint8_t m = read(ad); bool c = fC; fC = m & 1; m = (m >> 1) | (c << 7); write(ad, m); opAdcv(m); return 7; }
int CPU::op80() { pc++; return 2; }
int CPU::op81() { write(amIzx(), a); return 6; }
int CPU::op82() { pc++; return 2; }
int CPU::op83() { write(amIzx(), a & x); return 6; }
int CPU::op84() { write(amZp(), y); return 3; }
int NES_HOT CPU::op85() { write(amZp(), a); return 3; }
int CPU::op86() { write(amZp(), x); return 3; }
int CPU::op87() { write(amZp(), a & x); return 3; }
int NES_HOT CPU::op88() { y--; setZN(y); return 2; }
int CPU::op89() { pc++; return 2; }
int NES_HOT CPU::op8A() { a = x; setZN(a); return 2; }
int CPU::op8B() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::op8C() { write(amAbs(), y); return 4; }
int NES_HOT CPU::op8D() { write(amAbs(), a); return 4; }
int CPU::op8E() { write(amAbs(), x); return 4; }
int CPU::op8F() { write(amAbs(), a & x); return 4; }
int NES_HOT CPU::op90() { int cycles = 2; branch(!fC, cycles); return cycles; }
int CPU::op91() { write(amIzy(), a); return 6; }
int CPU::op92() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::op93() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::op94() { write(amZpx(), y); return 4; }
int CPU::op95() { write(amZpx(), a); return 4; }
int CPU::op96() { write(amZpy(), x); return 4; }
int CPU::op97() { write(amZpy(), a & x); return 4; }
int CPU::op98() { a = y; setZN(a); return 2; }
int NES_HOT CPU::op99() { write(amAby(), a); return 5; }
int CPU::op9A() { sp = x; return 2; }
int CPU::op9B() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::op9C() { return 2; }   // unimplemented: NOP, as the old default: did
int NES_HOT CPU::op9D() { write(amAbx(), a); return 5; }
int CPU::op9E() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::op9F() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::opA0() { opLdy(amImm()); return 2; }
int CPU::opA1() { opLda(amIzx()); return 6; }
int NES_HOT CPU::opA2() { opLdx(amImm()); return 2; }
int CPU::opA3() { a = x = read(amIzx()); setZN(a); return 6; }
int CPU::opA4() { opLdy(amZp()); return 3; }
int NES_HOT CPU::opA5() { opLda(amZp()); return 3; }
int CPU::opA6() { opLdx(amZp()); return 3; }
int CPU::opA7() { a = x = read(amZp()); setZN(a); return 3; }
int CPU::opA8() { y = a; setZN(y); return 2; }
int NES_HOT CPU::opA9() { opLda(amImm()); return 2; }
int CPU::opAA() { x = a; setZN(x); return 2; }
int CPU::opAB() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::opAC() { opLdy(amAbs()); return 4; }
int CPU::opAD() { opLda(amAbs()); return 4; }
int CPU::opAE() { opLdx(amAbs()); return 4; }
int CPU::opAF() { a = x = read(amAbs()); setZN(a); return 4; }
int NES_HOT CPU::opB0() { int cycles = 2; branch(fC, cycles); return cycles; }
int CPU::opB1() { opLda(amIzy()); return 5 + crossed_; }
int CPU::opB2() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::opB3() { a = x = read(amIzy()); setZN(a); return 5 + crossed_; }
int CPU::opB4() { opLdy(amZpx()); return 4; }
int NES_HOT CPU::opB5() { opLda(amZpx()); return 4; }
int CPU::opB6() { opLdx(amZpy()); return 4; }
int CPU::opB7() { a = x = read(amZpy()); setZN(a); return 4; }
int CPU::opB8() { fV = false; return 2; }
int CPU::opB9() { opLda(amAby()); return 4 + crossed_; }
int CPU::opBA() { x = sp; setZN(x); return 2; }
int CPU::opBB() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::opBC() { opLdy(amAbx()); return 4 + crossed_; }
int CPU::opBD() { opLda(amAbx()); return 4 + crossed_; }
int CPU::opBE() { opLdx(amAby()); return 4 + crossed_; }
int CPU::opBF() { a = x = read(amAby()); setZN(a); return 4 + crossed_; }
int CPU::opC0() { opCmpv(y, read(amImm())); return 2; }
int CPU::opC1() { opCmpv(a, read(amIzx())); return 6; }
int CPU::opC2() { pc++; return 2; }
int CPU::opC3() { uint16_t ad = amIzx(); uint8_t m = read(ad) - 1; write(ad, m); opCmpv(a, m); return 8; }
int CPU::opC4() { opCmpv(y, read(amZp())); return 3; }
int CPU::opC5() { opCmpv(a, read(amZp())); return 3; }
int CPU::opC6() { uint16_t ad = amZp(); uint8_t m = read(ad) - 1; write(ad, m); setZN(m); return 5; }
int CPU::opC7() { uint16_t ad = amZp(); uint8_t m = read(ad) - 1; write(ad, m); opCmpv(a, m); return 5; }
int NES_HOT CPU::opC8() { y++; setZN(y); return 2; }
int NES_HOT CPU::opC9() { opCmpv(a, read(amImm())); return 2; }
int NES_HOT CPU::opCA() { x--; setZN(x); return 2; }
int CPU::opCB() { uint8_t m = read(amImm()); int r = (a & x) - m; fC = r >= 0; x = (uint8_t)r; setZN(x); return 2; }
int CPU::opCC() { opCmpv(y, read(amAbs())); return 4; }
int CPU::opCD() { opCmpv(a, read(amAbs())); return 4; }
int CPU::opCE() { uint16_t ad = amAbs(); uint8_t m = read(ad) - 1; write(ad, m); setZN(m); return 6; }
int CPU::opCF() { uint16_t ad = amAbs(); uint8_t m = read(ad) - 1; write(ad, m); opCmpv(a, m); return 6; }
int NES_HOT CPU::opD0() { int cycles = 2; branch(!fZ, cycles); return cycles; }
int CPU::opD1() { opCmpv(a, read(amIzy())); return 5 + crossed_; }
int CPU::opD2() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::opD3() { uint16_t ad = amIzy(); uint8_t m = read(ad) - 1; write(ad, m); opCmpv(a, m); return 8; }
int CPU::opD4() { pc++; return 4; }
int CPU::opD5() { opCmpv(a, read(amZpx())); return 4; }
int CPU::opD6() { uint16_t ad = amZpx(); uint8_t m = read(ad) - 1; write(ad, m); setZN(m); return 6; }
int CPU::opD7() { uint16_t ad = amZpx(); uint8_t m = read(ad) - 1; write(ad, m); opCmpv(a, m); return 6; }
int CPU::opD8() { fD = false; return 2; }
int CPU::opD9() { opCmpv(a, read(amAby())); return 4 + crossed_; }
int CPU::opDA() { return 2; }
int CPU::opDB() { uint16_t ad = amAby(); uint8_t m = read(ad) - 1; write(ad, m); opCmpv(a, m); return 7; }
int CPU::opDC() { amAbx(); return 4 + crossed_; }
int CPU::opDD() { opCmpv(a, read(amAbx())); return 4 + crossed_; }
int CPU::opDE() { uint16_t ad = amAbx(); uint8_t m = read(ad) - 1; write(ad, m); setZN(m); return 7; }
int CPU::opDF() { uint16_t ad = amAbx(); uint8_t m = read(ad) - 1; write(ad, m); opCmpv(a, m); return 7; }
int NES_HOT CPU::opE0() { opCmpv(x, read(amImm())); return 2; }
int CPU::opE1() { opAdcv(~read(amIzx())); return 6; }
int CPU::opE2() { pc++; return 2; }
int CPU::opE3() { uint16_t ad = amIzx(); uint8_t m = read(ad) + 1; write(ad, m); opAdcv(~m); return 8; }
int CPU::opE4() { opCmpv(x, read(amZp())); return 3; }
int NES_HOT CPU::opE5() { opAdcv(~read(amZp())); return 3; }
int CPU::opE6() { uint16_t ad = amZp(); uint8_t m = read(ad) + 1; write(ad, m); setZN(m); return 5; }
int CPU::opE7() { uint16_t ad = amZp(); uint8_t m = read(ad) + 1; write(ad, m); opAdcv(~m); return 5; }
int NES_HOT CPU::opE8() { x++; setZN(x); return 2; }
int CPU::opE9() { opAdcv(~read(amImm())); return 2; }
int CPU::opEA() { return 2; }
int CPU::opEB() { opAdcv(~read(amImm())); return 2; }
int CPU::opEC() { opCmpv(x, read(amAbs())); return 4; }
int CPU::opED() { opAdcv(~read(amAbs())); return 4; }
int CPU::opEE() { uint16_t ad = amAbs(); uint8_t m = read(ad) + 1; write(ad, m); setZN(m); return 6; }
int CPU::opEF() { uint16_t ad = amAbs(); uint8_t m = read(ad) + 1; write(ad, m); opAdcv(~m); return 6; }
int NES_HOT CPU::opF0() { int cycles = 2; branch(fZ, cycles); return cycles; }
int CPU::opF1() { opAdcv(~read(amIzy())); return 5 + crossed_; }
int CPU::opF2() { return 2; }   // unimplemented: NOP, as the old default: did
int CPU::opF3() { uint16_t ad = amIzy(); uint8_t m = read(ad) + 1; write(ad, m); opAdcv(~m); return 8; }
int CPU::opF4() { pc++; return 4; }
int CPU::opF5() { opAdcv(~read(amZpx())); return 4; }
int CPU::opF6() { uint16_t ad = amZpx(); uint8_t m = read(ad) + 1; write(ad, m); setZN(m); return 6; }
int CPU::opF7() { uint16_t ad = amZpx(); uint8_t m = read(ad) + 1; write(ad, m); opAdcv(~m); return 6; }
int CPU::opF8() { fD = true; return 2; }
int CPU::opF9() { opAdcv(~read(amAby())); return 4 + crossed_; }
int CPU::opFA() { return 2; }
int CPU::opFB() { uint16_t ad = amAby(); uint8_t m = read(ad) + 1; write(ad, m); opAdcv(~m); return 7; }
int CPU::opFC() { amAbx(); return 4 + crossed_; }
int CPU::opFD() { opAdcv(~read(amAbx())); return 4 + crossed_; }
int CPU::opFE() { uint16_t ad = amAbx(); uint8_t m = read(ad) + 1; write(ad, m); setZN(m); return 7; }
int CPU::opFF() { uint16_t ad = amAbx(); uint8_t m = read(ad) + 1; write(ad, m); opAdcv(~m); return 7; }

// Dispatch table: index is the opcode byte.
const CPU::OpFn CPU::OPS[256] = {
    &CPU::op00, &CPU::op01, &CPU::op02, &CPU::op03, &CPU::op04, &CPU::op05, &CPU::op06, &CPU::op07, &CPU::op08, &CPU::op09, &CPU::op0A, &CPU::op0B, &CPU::op0C, &CPU::op0D, &CPU::op0E, &CPU::op0F,
    &CPU::op10, &CPU::op11, &CPU::op12, &CPU::op13, &CPU::op14, &CPU::op15, &CPU::op16, &CPU::op17, &CPU::op18, &CPU::op19, &CPU::op1A, &CPU::op1B, &CPU::op1C, &CPU::op1D, &CPU::op1E, &CPU::op1F,
    &CPU::op20, &CPU::op21, &CPU::op22, &CPU::op23, &CPU::op24, &CPU::op25, &CPU::op26, &CPU::op27, &CPU::op28, &CPU::op29, &CPU::op2A, &CPU::op2B, &CPU::op2C, &CPU::op2D, &CPU::op2E, &CPU::op2F,
    &CPU::op30, &CPU::op31, &CPU::op32, &CPU::op33, &CPU::op34, &CPU::op35, &CPU::op36, &CPU::op37, &CPU::op38, &CPU::op39, &CPU::op3A, &CPU::op3B, &CPU::op3C, &CPU::op3D, &CPU::op3E, &CPU::op3F,
    &CPU::op40, &CPU::op41, &CPU::op42, &CPU::op43, &CPU::op44, &CPU::op45, &CPU::op46, &CPU::op47, &CPU::op48, &CPU::op49, &CPU::op4A, &CPU::op4B, &CPU::op4C, &CPU::op4D, &CPU::op4E, &CPU::op4F,
    &CPU::op50, &CPU::op51, &CPU::op52, &CPU::op53, &CPU::op54, &CPU::op55, &CPU::op56, &CPU::op57, &CPU::op58, &CPU::op59, &CPU::op5A, &CPU::op5B, &CPU::op5C, &CPU::op5D, &CPU::op5E, &CPU::op5F,
    &CPU::op60, &CPU::op61, &CPU::op62, &CPU::op63, &CPU::op64, &CPU::op65, &CPU::op66, &CPU::op67, &CPU::op68, &CPU::op69, &CPU::op6A, &CPU::op6B, &CPU::op6C, &CPU::op6D, &CPU::op6E, &CPU::op6F,
    &CPU::op70, &CPU::op71, &CPU::op72, &CPU::op73, &CPU::op74, &CPU::op75, &CPU::op76, &CPU::op77, &CPU::op78, &CPU::op79, &CPU::op7A, &CPU::op7B, &CPU::op7C, &CPU::op7D, &CPU::op7E, &CPU::op7F,
    &CPU::op80, &CPU::op81, &CPU::op82, &CPU::op83, &CPU::op84, &CPU::op85, &CPU::op86, &CPU::op87, &CPU::op88, &CPU::op89, &CPU::op8A, &CPU::op8B, &CPU::op8C, &CPU::op8D, &CPU::op8E, &CPU::op8F,
    &CPU::op90, &CPU::op91, &CPU::op92, &CPU::op93, &CPU::op94, &CPU::op95, &CPU::op96, &CPU::op97, &CPU::op98, &CPU::op99, &CPU::op9A, &CPU::op9B, &CPU::op9C, &CPU::op9D, &CPU::op9E, &CPU::op9F,
    &CPU::opA0, &CPU::opA1, &CPU::opA2, &CPU::opA3, &CPU::opA4, &CPU::opA5, &CPU::opA6, &CPU::opA7, &CPU::opA8, &CPU::opA9, &CPU::opAA, &CPU::opAB, &CPU::opAC, &CPU::opAD, &CPU::opAE, &CPU::opAF,
    &CPU::opB0, &CPU::opB1, &CPU::opB2, &CPU::opB3, &CPU::opB4, &CPU::opB5, &CPU::opB6, &CPU::opB7, &CPU::opB8, &CPU::opB9, &CPU::opBA, &CPU::opBB, &CPU::opBC, &CPU::opBD, &CPU::opBE, &CPU::opBF,
    &CPU::opC0, &CPU::opC1, &CPU::opC2, &CPU::opC3, &CPU::opC4, &CPU::opC5, &CPU::opC6, &CPU::opC7, &CPU::opC8, &CPU::opC9, &CPU::opCA, &CPU::opCB, &CPU::opCC, &CPU::opCD, &CPU::opCE, &CPU::opCF,
    &CPU::opD0, &CPU::opD1, &CPU::opD2, &CPU::opD3, &CPU::opD4, &CPU::opD5, &CPU::opD6, &CPU::opD7, &CPU::opD8, &CPU::opD9, &CPU::opDA, &CPU::opDB, &CPU::opDC, &CPU::opDD, &CPU::opDE, &CPU::opDF,
    &CPU::opE0, &CPU::opE1, &CPU::opE2, &CPU::opE3, &CPU::opE4, &CPU::opE5, &CPU::opE6, &CPU::opE7, &CPU::opE8, &CPU::opE9, &CPU::opEA, &CPU::opEB, &CPU::opEC, &CPU::opED, &CPU::opEE, &CPU::opEF,
    &CPU::opF0, &CPU::opF1, &CPU::opF2, &CPU::opF3, &CPU::opF4, &CPU::opF5, &CPU::opF6, &CPU::opF7, &CPU::opF8, &CPU::opF9, &CPU::opFA, &CPU::opFB, &CPU::opFC, &CPU::opFD, &CPU::opFE, &CPU::opFF,
};
// clang-format on

int NES_HOT CPU::step() {
    if (stall_ > 0) { int s = stall_; stall_ = 0; return s; }

    if (nmiPending_) {
        nmiPending_ = false;
        push(pc >> 8); push(pc & 0xFF);
        push(status(false));
        fI = true;
        pc = read16(0xFFFA);
        return 7;
    }
    if (irqLine_ && !fI) {
        push(pc >> 8); push(pc & 0xFF);
        push(status(false));
        fI = true;
        pc = read16(0xFFFE);
        return 7;
    }

    // Cleared here rather than in each addressing helper: only the abx/aby/izy
    // modes set it, and the opcodes that use them are exactly the ones that read
    // it back, so a single reset per instruction matches the old local variable.
    crossed_ = false;
    const uint8_t op = read(pc++);
#ifdef NES_CPU_COUNT_OPS
    g_opCounts[op]++;   // opcode-frequency profiling only; never on in a real build
#endif
    return (this->*OPS[op])();
}

} // namespace nes
