[env:m5stack-cores3]
platform = espressif32@^6.7.0
board = m5stack-cores3
framework = arduino
lib_deps =
    m5stack/M5Unified@^0.2.2
    nes-core=symlink://../core
build_unflags = -std=gnu++11 -Os
build_flags = -std=gnu++17 -O2 -DNES_EMBEDDED -DBOARD_HAS_PSRAM -DNES_PROFILE
board_build.embed_files = data/game.nes
monitor_speed = 115200
